### ISSUE TITLE
Why calculate these distances for only outside does?

### ISSUE THREAD

**Issue by kaitlyngaynor** [skreling/Hopland_Fire_Deer#3]
I'm trying to review the scripts & make sure everything runs. I'm having some issues running this and was going to just move this analysis over to the MCP_Centroid_Generation script to keep it all together, since we calculate all of the centroids over there. But I wanted to check in with you first and just ask WHY we are calculating displacement only for does outside of the fire perimeter here? I'm trying to figure out how it fits in with the rest of the analysis- let me know if you have insights!

getting closer...

**Comment by skreling** [comment]
What script is this referring to?

**Comment by kaitlyngaynor** [comment]
Oh oops, I meant to quote the script. I was referring to this bit:

https://github.com/skreling/Hopland_Fire_Deer/blob/57e2c28cd2cc8836f9c0596f10126d2983bca938/Publication_Rcode/Collars5_Homerange_Displacement.R#L52-L108

**Comment by skreling** [comment]
Not sure if you are referring to why I calculated it separately or why I calculated it at all?

But to answer the first question (I think) 1) The mcp shapefiles only have mcps for the does inside the fire perimeter, thus they only have centroids for those does when we calculate them. I'm not actually 100% sure why I calculated the centroids from the already made mcps for the in fire does, could have just done it from the collars, but did not for whatever reason. 

Question 2) Wanted to know if does outside the fire moved from their homeranges after the fire as sort of a comparison to deer inside of the fire definitely moving around more presumably because of the fire if that makes sense.

**Comment by kaitlyngaynor** [comment]
Hmm okay trying to wrap my head around what these scripts do:

The script now called "Collars3_MCP_Centroid_Generation" reads in the animal location points and creates MCPs with adeHabitatHR. The centroid of each MCP is then calculated, and exported in MCP_Centroid.csv for the Pre and Post periods (for all animals). Unclear to me if/how this csv is used in subsequent analysis.

The script now called "Collars4_Homerange_Displacement" then pulls in MCP shapefiles (not sure where they came from?) and then re-calculates centroids & distances, in slightly different ways for the deer in and out. I guess I'm just wondering why, instead, you don't use the centroids generated in the previous script to calculate this distance? (And what the purpose of the previous script is otherwise?)

Sorry if that is confusing! Let me know if I'm totally missing something. Pretty close to figuring this all out!

**Comment by skreling** [comment]
Oh! Got it. Script 3 creates the 'MCP_Centroids.csv' and in Script 4 I used the 'MCP_Centroids.csv' and the 'far.csv' files to create a distance matrix in QGIS to create the 'distances.csv' files that we import in script 4. At the top of script 4 I have a little annotation that explains that part.

I made the distance matrix for that in QGIS because R kept throwing an issue at me that I couldn't figure out even though the same code had worked prior and when I did it in QGIS I got the same values I had previously obtained from the R code before it broke.

**Comment by kaitlyngaynor** [comment]
> Oh! Got it. Script 3 creates the 'MCP_Centroids.csv' and in Script 4 I used the 'MCP_Centroids.csv' and the 'far.csv' files to create a distance matrix in QGIS to create the 'distances.csv' files that we import in script 4. At the top of script 4 I have a little annotation that explains that part.

Ah okay sorry missed that.

> I made the distance matrix for that in QGIS because R kept throwing an issue at me that I couldn't figure out even though the same code had worked prior and when I did it in QGIS I got the same values I had previously obtained from the R code before it broke.

Can we just delete all of the code below line 23 then? That's the part that I'm confused about. Not sure what it's doing.

**Comment by kaitlyngaynor** [comment]
I am thinking I'll just pull the top bit of script 4 (lines 12-19) into the bottom of script 3 and then ditch the rest?

**Comment by skreling** [comment]
Ok now i'm a little confused... In script 4 lines 10-20 calculate displacement during fire so that's important to move over to script 3. Script 3 does not do distance matrices so that would need to be added in if we merged scripts.

**Comment by kaitlyngaynor** [comment]
> Ok now i'm a little confused... In script 4 lines 10-20 calculate displacement during fire so that's important to move over to script 3. 

Ah sorry for the confusion! Originally lines 10-20 were in their own little script and they seemed lonely so I was trying to find a home for them. 

> Script 3 does not do distance matrices so that would need to be added in if we merged scripts.

But didn't you say you just did the distance matrix in QGIS? We can leave your note in there and just leave it at that. Alternatively, I can integrate that code at the bottom of script 4 into script 3 (before that chunk in lines 10-20). Not sure it matters much either way.

At any rate, I think I understand what's going on now! I'll poke around a little bit more. thanks for clarifying!

**Comment by skreling** [comment]
Oh theres 3 different distance matrices. The one for during fire I did in QGIS because it wasn't working for whatever reason. The other 2 compare prefire inside doe with postfire inside doe and prefire outside doe with postfire outside doe. Sorry I probably could have made this clearer.

The pre/post fire could have been done together. I think I just did it for ease of not having to filter it out later and because I pulled centroids from two sources for whatever reason.

**Comment by kaitlyngaynor** [comment]
ooooooooooh

**Comment by kaitlyngaynor** [comment]
Ok, to make things easier, I just calculated the distances immediately after the centroids were calculated in the script 3. I got the same exact mean/SD for the outside does, and a VERY similar value for the t-test, but slightly different because of the way the inside doe centroids were re-calculated, I think. For consistency, I think it makes sense to use the code that I wrote—would you agree? Have a look below at the means, SD, and t-test results, which would need to be integrated into the manuscript.

https://github.com/skreling/Hopland_Fire_Deer/blob/5fcfefa98201989dd9006dce6d659eb7d9c9bb19/Publication_Rcode/Collars3_MCP_Centroid_Generation.Rmd#L95-L127

**Comment by kaitlyngaynor** [comment]
This is the paragraph that needs updating. I've bolded the new numbers. The only thing that changed significantly was the SD of the does inside, which is weird?

While home range size increased after the fire, the location of the home ranges of individual female deer did not change significantly when compared with female deer outside the burn perimeter (t = **0.40**, p = 0.7**0**, df = 5.4**9**). On average, the centroid of female deer home ranges (n= 11) within the fire shifted by **140.32** m (SD = **67.97** m), and the two male deer home ranges shifted by 30.13 and 36.10 m. Female deer outside the burn perimeter (n = 5) shifted their home ranges on average by 119.2**1** m (SD = 108.37).

**Comment by skreling** [comment]
Sure thing that works for me! I updated it. Yeah really not sure why the SD changed that much?
