### ISSUE TITLE
Github oops

### ISSUE THREAD

**Issue by skreling** [skreling/Hopland_Fire_Deer#8]
Hey K, 

I made a rookie github move but think I fixed it, but in case something arises on your end let me know and i'll figure it out

**Comment by kaitlyngaynor** [comment]
Was able to pull successfully! 

In general, I think it's good to avoid putting binary data formats like .docx in git repositories since they don't lend themselves well to the way that git tracks changes to files. It can, over the long term, end up eating up a ton of hard drive space since you'll have every old version of a file in your local repo and it's quite hard to expunge. Same goes for data files too. It's fine here, since we're nearing the end and these files are small, but just a heads up for the future
